name: deploy-auth

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'packages/auth/dist'
          destination: ${{ secrets.PRODUCTION_BUCKET }}/auth/latest
          parent: false
      - name: "Invalidate cache"
        run: gcloud compute url-maps invalidate-cdn-cache ${{ secrets.GCP_LOAD_BALANCER_NAME }} --path "/auth/latest/remoteEntry.js"
