name: deploy-marketing

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'packages/marketing'
          destination: ${{ secrets.PRODUCTION_BUCKET }}/marketing/latest
          parent: false

#      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
